services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: owner
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  
    volumes:
      -  /root/projects/api_project/tmp/db:/var/lib/postgresql/data
      
  web:
    build: 
      context: .
    command: bundle exec rails s -b 0.0.0.0 
    volumes:
      - /root/projects/api_project:/app
    working_dir:  /app  
    ports:
      - "3000:3000"
    depends_on:
      - postgres 
volumes:
  postgres:      
