default: &default
  adapter: postgresql
  encoding: unicode
  username: owner
  password: postgres
  database: postgresql
  host: postgresql
  post: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default